// Auto-generated OP17 spoiler cards (source: opdeckguide.com, 2026-08-02)
window.CUSTOM_CARDS = [
 {
  "id": "OP17-001",
  "name": "Edward Newgate",
  "text": "[On Your Opponent's Attack] [Once Per Turn] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +4000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "L",
  "color": "Red",
  "type": "Leader",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-001.png",
  "spoiler": true
 },
 {
  "id": "OP17-002",
  "name": "Atmos",
  "text": "[Opponent's Turn] This Character gains +3000 power.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-002.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-003",
  "name": "Izo",
  "text": "[Rush] Character [On Play] If your Leader is [Edward Newgate] or has the {Land of Wano} type, give up to 1 of your opponent&#39;s rested Characters -6000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-003.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-004",
  "name": "Inuarashi &amp; Nekomamushi",
  "text": "[On Play] Up to 1 of your {Land of Wano} type Characters or up to 1 of your Characters with a type including &quot;Whitebeard Pirates&quot; gains [Rush] during this turn. (This card can attack on the turn in which it is played.)",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-004.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-005",
  "name": "Edward Newgate",
  "text": "If your opponent has a Character with 10000 power or more, give this card in your hand -4 cost. [On Play] Set the base power of your monocolored Leader to 8000 until the end of your opponent&#39;s next End Phase.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-005.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-006",
  "name": "Kingdew",
  "text": "",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-006.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-007",
  "name": "Kouzuki Oden",
  "text": "[On Play] If your Leader is [Edward Newgate] or has the {Land of Wano} type, play up to 1 Character card with a type including {Land of Wano} or &quot;Whitebeard Pirates&quot; with 6000 power or less from your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-007.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-008",
  "name": "Jozu",
  "text": "[On Play] Your [Edward.Newgate] Leader&#39;s base power becomes 8000 until the end of your opponent&#39;s next End Phase.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-008.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-012",
  "name": "Blenheim",
  "text": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.) [On K.O.] Play up to 1 card with a cost of 1 and a type including &quot;Whitebeard Pirates&quot; from your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-012.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-013",
  "name": "Portgas.D.Ace",
  "text": "If your opponent has a Character with 10000 power or more, give this card in your hand -2 cost. [On Play] If your Leader is [Edward.Newgate], give up to 1 of your opponent&#39;s rested Characters -6000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-013.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-015",
  "name": "Marco",
  "text": "If one of your Characters would be removed from the field by your opponent&#39;s effect, you may K.O. this Character instead. [On K.O.] You may trash 1 card with a type including &quot;Whitebeard Pirates&quot; from your hand: Play this Character card from your trash.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-015.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-019",
  "name": "I Don&#39;t Have Time to Chat with Snot-Nosed Brats",
  "text": "[Main] Look at 5 cards from the top of your deck; reveal up to 1 card with a type including &quot;Whitebeard Pirates&quot; and add it to your hand. Then, place the rest at the bottom of your deck in any order. [Trigger] Your Leader gains +1000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Red",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-019.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-020",
  "name": "Shanks",
  "text": "[Activate: Main] [Once Per Turn] You may trash 1 card from your hand or rest 1 of your DON!! cards: Up to 1 of your opponent&#39;s rested Characters will not become active during your opponent&#39;s next Refresh Phase.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "L",
  "color": "Green",
  "type": "Leader",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-020.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-022",
  "name": "Shanks",
  "text": "[Rush] [On Play] Set up to 2 of your DON!! cards as active. Then, rest all of your opponent&#39;s Characters.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-022.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-024",
  "name": "Howling Gab",
  "text": "[Banish] (When this card deals damage, the target card is trashed without activating its Trigger.) [On Play] Rest up to 1 of your opponent&#39;s Characters.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-024.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-025",
  "name": "Building Snake",
  "text": "[On K.O.] K.O. up to 1 of your opponent&#39;s rested Characters with a cost of 6 or less. [Activate: Main] [Once Per Turn] Give up to 1 rested DON!! card to your [Shanks] Leader.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-025.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-026",
  "name": "Fugar",
  "text": "[When Attacking] If your Leader has the {Red-Haired Pirates} type, rest up to 1 of your opponent&#39;s Characters with a cost of 2 or less. [On K.O.] Draw 1 card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-026.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-027",
  "name": "Benn Beckman",
  "text": "[Rush]: Character (This card can attack Characters on the turn it is played.) [On Play] If your Leader has the {Red-Haired Pirates} type, draw 1 card and rest up to 2 of your opponent&#39;s Characters.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-027.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-028",
  "name": "Bonk Punch &amp; Monster",
  "text": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.) [On Play] K.O. up to 1 of your opponent&#39;s rested Characters with a cost of 6 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-028.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-029",
  "name": "Hongo",
  "text": "[Blocker] [On Play] Set up to 1 of your DON!! cards as active. Then, rest up to 2 of your opponent&#39;s Characters with a cost of 2 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-029.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-030",
  "name": "Monkey.D.Luffy",
  "text": "[On Play] You may rest 1 of your DON!! cards: This Character gains [Rush] during this turn. [Activate: Main] [Once Per Turn] If you have 5 or less cards in your hand, set up to 1 of your DON!! cards as active.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-030.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-031",
  "name": "Yasopp",
  "text": "[On Play] Draw 1 card and rest up to 1 of your opponent&#39;s Characters with a cost of 8 or less. [End of Your Turn] Set up to 1 of your {Red-Haired Pirates} type Characters as active.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-031.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-032",
  "name": "Lime Juice",
  "text": "[On Play] Look at 3 cards from the top of your deck; reveal up to 1 card with a type including &quot;Red-Haired Pirates&quot; and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-032.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-033",
  "name": "Lucky.Roux",
  "text": "[On Play] Look at 3 cards from the top of your deck; reveal up to 1 card with a type including &quot;Red-Haired Pirates&quot; and add it to your hand. Then, place the rest at the bottom of your deck in any order. [On Your Opponent's Attack] You may trash this Character: Rest up to 1 of your opponent&#39;s Leader or Characters.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-033.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-034",
  "name": "Rockstar",
  "text": "[Activate: Main] [Once Per Turn] If your opponent&#39;s Leader has 6000 power or more, set up to 1 of your DON!! cards as active. Then, your {Red-Haired Pirates} type Leader&#39;s base power becomes 6000 until the end of your opponent&#39;s next End Phase.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Green",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-034.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-035",
  "name": "Roronoa Zoro",
  "text": "",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-035.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-037",
  "name": "Are You That Afraid of the New Era?!!",
  "text": "[Main] Look at 5 cards from the top of your deck; reveal up to 1 card with a type including &quot;Red-Haired Pirates&quot; and add it to your hand. Then, place the rest at the bottom of your deck in any order. [Counter] You may rest 1 of your cards: Up to 1 of your Leader or Characters gains +3000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Red",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-037.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-038",
  "name": "I Think He&#39;s Seen An Ugly Future",
  "text": "[Main] You may rest 4 of your cards: Rest up to 1 of your opponent&#39;s Characters. [Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Green",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-038.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-039",
  "name": "Rocks.D.Xebec",
  "text": "[When Attacking] You may trash 1 card from your hand: Reveal 1 card from the top of your deck. If the revealed card&#39;s type includes &quot;Rocks Pirates&quot;, draw 2 cards.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "L",
  "color": "Blue",
  "type": "Leader",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-039.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-041",
  "name": "Wang Zhi",
  "text": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.) [On Play] You may trash 1 card from your hand: Place all of your opponent&#39;s Characters with a base cost of 1 at the bottom of the owner&#39;s deck in any order.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-041.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-042",
  "name": "Kaido",
  "text": "[Blocker] [On Play] You may reveal 3 cards with a type including &quot;Rocks Pirates&quot; from your hand: Give up to 1 of your opponent&#39;s Characters -3000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-042.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-043",
  "name": "Ganzui",
  "text": "If this Character would be removed from the field, you may trash 2 cards from your hand instead. [On Play] Your Leader&#39;s base power becomes 6000 until the end of your opponent&#39;s next End Phase.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-043.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-044",
  "name": "Captain John",
  "text": "If your Leader&#39;s type includes &quot;Rocks Pirates&quot; and this Character is rested, your opponent cannot attack any card other than the Character [Captain John]. [Activate: Main] You may rest this Character: Draw 1 card and trash 1 card from your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-044.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-045",
  "name": "Kyo",
  "text": "If one of your Characters would be removed from the field by your opponent&#39;s effect, you may trash 2 cards from your hand instead. [On Play] Draw 1 card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-045.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-046",
  "name": "Gloriosa",
  "text": "[Blocker] [On Play] Place up to 1 Character with a cost of 5 or less at the bottom of the owner&#39;s deck.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-046.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-048",
  "name": "Shiki",
  "text": "[Rush: Character] [When Attacking] / [On Your Opponent's Attack] [Once Per Turn] You may trash 1 card with a type including &quot;Rocks Pirates&quot; from your hand: Give up to 1 of your opponent&#39;s Characters -3000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-048.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-049",
  "name": "Charlotte Linlin",
  "text": "[On Play] Your opponent chooses one: - Draw 2 cards. - Your opponent trashes 2 cards from their hand. [On Your Opponent's Attack] [Once Per Turn] You may trash 1 card from your hand: Up to 1 of your Leader or Characters gains +1000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-049.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-050",
  "name": "Streusen",
  "text": "[On Play] Look at 2 cards from the top of your deck, reorganize them in any order and place them at the top or bottom of your deck. Then, draw 1 card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-050.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-051",
  "name": "Jinbe",
  "text": "",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-051.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-052",
  "name": "Don Marlon",
  "text": "[On Play] Add up to 1 blue Event with a cost of 0 from your trash to your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-052.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-053",
  "name": "Barbell",
  "text": "[On K.O.] Your opponent places 2 cards from their hand at the bottom of their deck in any order. [Activate: Main] [Once Per Turn] You may trash 1 card from your hand: This Character gains +3000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-053.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-054",
  "name": "Miss Buckingham Stussy",
  "text": "[On Play] Up to 1 of your opponent&#39;s Characters with a base cost of 6 or less cannot attack until the end of your opponent&#39;s next End Phase. [Activate: Main] You may rest 3 of your DON!! cards and this Character: Up to 1 of your opponent&#39;s Characters cannot attack until the end of your opponent&#39;s next End Phase.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-054.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-055",
  "name": "There&#39;s No Authority in the World That Lasts Forever!!!",
  "text": "[Main] You may rest 1 of your DON!! cards: Up to 1 of your [Rocks.D.Xebec] gains [Unblockable] during this turn. [Counter] Up to 1 of your Leader with a type including &quot;Rocks Pirates&quot; or up to 1 of your Characters with a type including &quot;Rocks Pirates&quot; gains +2000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Blue",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-055.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-056",
  "name": "Rocks Pirates",
  "text": "[Main] You may rest 5 of your DON!! cards: Return up to 1 Character with a cost of 6 or less to the owner&#39;s hand. [Counter] Up to 1 of your Leader with a type including &quot;Rocks Pirates&quot; or up to 1 of your Characters with a type including &quot;Rocks Pirates&quot; gains +2000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Blue",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-056.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-057",
  "name": "Fullalead",
  "text": "[On Your Opponent's Attack] You may rest this Stage and trash 1 card from your hand: Up to 1 of your Leader with a type including &quot;Rocks Pirates&quot; or up to 1 of your Characters with a type including &quot;Rocks Pirates&quot; gains +1000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-057.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-058",
  "name": "Kaido",
  "text": "[When Attacking] / [On Your Opponent's Attack] [Once Per Turn] DON!! -1: Up to 1 of your opponent&#39;s Characters gets -2000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "L",
  "color": "Purple",
  "type": "Leader",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-058.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-059",
  "name": "Aramaki",
  "text": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.) [On Play] DON!! -1: Draw 1 card and K.O. up to 2 of your opponent&#39;s Characters with a cost of 2 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-059.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-060",
  "name": "Ulti &amp; Page One",
  "text": "[On Play] If your Leader has the {Animal Kingdom Pirates} type, add up to 1 DON!! from your DON!! deck and set it as active. Then, K.O. up to 1 of your opponent&#39;s Characters with 3000 power or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-060.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-061",
  "name": "Lead Performers",
  "text": "[On Play] DON!! -1: If your Leader has the {Animal Kingdom Pirates} type, add up to 1 card from the top of your deck to the top of your Life cards. [Activate: Main] You may trash this Character: Play up to 1 [King], [Queen], or [Jack] from your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-061.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-062",
  "name": "Kaido",
  "text": "[Blocker] [Your Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck, add up to 1 DON!! card from your DON!! deck and set it as active. Then, set up to 1 of your DON!! cards as active.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-062.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-063",
  "name": "Kaido",
  "text": "All of your Character cards without a Counter in your hand have a +1000 Counter. [Activate: Main] [Once Per Turn] DON!! -1: If this Character was played on this turn, negate the effect of up to 1 of your opponent&#39;s Characters with a cost of 6 or less, and K.O. that Character.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-063.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-064",
  "name": "King",
  "text": "[Blocker] [On Your Opponent's Attack] [Once Per Turn] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +2000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-064.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-066",
  "name": "Kurozumi Orochi",
  "text": "[On Play] DON!! -1: If you have a Character with a cost of 10 or more, draw 2 cards and trash 1 card from your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-066.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-071",
  "name": "Who&#39;s.Who",
  "text": "[On Play] DON!! -1: K.O. up to 2 of your opponent&#39;s Characters with a cost of 2 or less. [Trigger] Play this card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-071.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-072",
  "name": "Black Maria",
  "text": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.) [On Your Opponent's Attack] [Once Per Turn] You may trash 1 card from your hand: Up to 1 of your Leader or Characters gains +1000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-072.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-074",
  "name": "Yamato",
  "text": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.) [On Play] Add up to 1 DON!! card as rested from your DON!! deck.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Purple",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-074.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-078",
  "name": "Drunken Dragon Bagua",
  "text": "[Main] You may rest 2 of your DON!! cards and trash 2 cards from your hand: If your Leader has the {Animal Kingdom Pirates} type, add up to 3 DON!! cards from your DON!! deck and rest them. [Counter] Give up to 1 of your Leader or Character cards +4000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Purple",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-078.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-079",
  "name": "Monkey D. Luffy",
  "text": "All of your characters with a cost of 12 or more gain [Blocker]. (After your opponent attacks, you can rest this card and target this card for the next attack.)",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "L",
  "color": "Black",
  "type": "Leader",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-079.png",
  "spoiler": true
 },
 {
  "id": "OP17-080",
  "name": "Usopp",
  "text": "If there is a Character with a cost of 12 or more, this Character gains +3000 power. [On Play] Look at the top 3 cards of your deck, reveal up to 1 {Elbaf} type card and add it to your hand. Then, trash the rest.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-080.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-081",
  "name": "Gerd",
  "text": "If your Leader has the {Elbaph} type, this Character gains +12 cost. [On Play] You may trash 1 card from your hand: add up to 1 Character with a cost of 8 or less from your trash other than [Gerd] to your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Black Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-081.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-082",
  "name": "Sanji",
  "text": "If there is a Character with a cost of 12 or more, this Character gains +3000 power. [On Play] Draw 2 cards and trash 2 cards from your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-082.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-083",
  "name": "Jinbe",
  "text": "If there is a Character with a cost of 12 or more, this Character gains [Blocker] and +3000 power. (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-083.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-084",
  "name": "Tony Tony.Chopper",
  "text": "[On Play] If there is a Character with a cost of 12 or more, up to 1 of your Characters gains [Unblockable] during this turn. (This card cannot be blocked.)",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-084.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-085",
  "name": "Nami",
  "text": "[On Play] You may trash 1 {Elbaph} type card from your hand: Draw 2 cards.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Black Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-085.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-087",
  "name": "Nico Robin",
  "text": "If there is a Character with a cost of 12 or more, this Character gains +3000 power. [On Play] If there is a Character with a cost of 12 or more, give up to 1 of your opponent&#39;s Characters -3000 power during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-087.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-089",
  "name": "Jaguar D. Saul",
  "text": "This Character gains +12 cost. [On Play] Look at 3 cards from the top of your deck; reveal up to 1 {Elbaph} type card and add it to your hand. Then, trash the rest.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-089.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-090",
  "name": "Franky",
  "text": "If there is a Character with a cost of 12 or more, this Character gains +3000 power. [On Play] If there is a Character with a cost of 12 or more, K.O. up to 1 of your opponent&#39;s Characters with a cost of 2 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-090.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-091",
  "name": "Brook",
  "text": "If there is a Character with a cost of 12 or more, this Character gains +3000 power. [On Play] If there is a Character with a cost of 12 or more, your opponent trashes 1 card from their hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-091.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-092",
  "name": "Brogy",
  "text": "This Character gains +12 cost. [On Play] If your Leader has the {Elbaph} type, play up to 1 [Dorry] with a cost of 5 or less from your trash or your hand. Then, you cannot play Character cards during this turn.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-092.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-093",
  "name": "Monkey D. Luffy",
  "text": "If there is a character with a cost of 12 or more, this character gains [Rush]. [On Play] Draw one card, and play up to one character card with a cost of 2 or less from your trash.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-093.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-094",
  "name": "Rodo",
  "text": "If your Leader has the {Elbaph} type, this Character gains +12 cost.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-094.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-095",
  "name": "Roronoa Zoro",
  "text": "If there is a Character with a cost of 12 or more, this Character gains +3000 power. If one of your Characters would be removed from the field by your opponent&#39;s effect, you may place 3 cards from your trash at the bottom of your deck in any order instead.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Black",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-095.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-098",
  "name": "Gum-Gum Kong Pistol",
  "text": "[Main] You may rest 6 of your DON!! cards: If there is a Character with a cost of 12 or more, K.O. up to 2 of your opponent&#39;s Characters with a cost of 6 or less. [Counter] Your Leader gains +3000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Black",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-098.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-099",
  "name": "Charlotte.Linlin",
  "text": "[When Attacking] You may trash 1 card from your hand: Your opponent chooses one of the following effects. - Trash 1 card from your hand. Then, add up to 1 card from the top of your deck to the top of your Life cards. - Your opponent trashes 1 card from their hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "L",
  "color": "Yellow",
  "type": "Leader",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-099.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-101",
  "name": "Caribou",
  "text": "[Activate: Main] [Once Per Turn] You may add 1 card from the top of your Life cards to your hand: Give up to 1 of your opponent&#39;s Characters -3000 power during this turn. [Trigger] You may trash 1 card from your hand: K.O. up to 1 of your opponent&#39;s Characters with a cost of 5 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-101.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-103",
  "name": "Charlotte Katakuri",
  "text": "[Your Turn] [On Play] If your Leader has the {Big Mom Pirates} type, add up to 1 card from the top of your deck to the top of your Life cards. Then, give up to 1 of your opponent&#39;s Characters -3000 power during this turn. [Trigger] Play this card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-103.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-104",
  "name": "Charlotte Cracker",
  "text": "[Your Turn] [On Play] You may rest 2 of your DON!! cards: If your Leader has the {Big Mom Pirates} type, add up to 1 card from the top of your deck to the top of your Life cards. [Trigger] Play this card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-104.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-105",
  "name": "Charlotte Chiffon",
  "text": "[On Play] You may trash 1 card with a [Trigger] from your hand: Return up to 1 of your opponent&#39;s Characters with a [Trigger] to the owner&#39;s hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-105.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-106",
  "name": "Charlotte Smoothie",
  "text": "[Your Turn] [On Play] You may rest 2 of your DON!! cards: Add up to 1 card from the top of your deck to the top of your Life cards. Then, your opponent trashes 1 card from their hand. [Trigger] Play this card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-106.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-108",
  "name": "Charlotte Brulee",
  "text": "[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.) [Trigger] Rest up to 1 of your opponent&#39;s Characters with a cost of 6 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-108.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-109",
  "name": "Charlotte Pudding",
  "text": "[On Play] You may trash 1 card with a [Trigger] from your hand: Draw 3 cards. [Trigger] Look at 5 cards from the top of your deck; reveal up to 1 {Big Mom Pirates} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-109.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-112",
  "name": "Charlotte Linlin",
  "text": "[Your Turn] All of your Characters with 4000 base power and a [Trigger] become 8000 base power. [On Play] Draw 1 card and choose one of the following effects. - Add up to 1 card from the top of your deck to the top of your Life cards. - Add up to 1 card from the top of your opponent&#39;s Life cards to the owner&#39;s hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SR",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-112.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-113",
  "name": "Streusen",
  "text": "[On Play] Look at 3 cards from the top of your deck; reveal up to 1 {Big Mom Pirates} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-113.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-114",
  "name": "The 3 Sweet Commanders",
  "text": "[Your Turn] [On Play] You may rest 2 of your DON!! cards: Draw 1 card and add up to 1 card from the top of your deck to the top of your Life. Then, give up to 2 of your opponent&#39;s Characters -3000 power during this turn. [Trigger] Play this card.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "R",
  "color": "Yellow",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-114.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-116",
  "name": "Fulgora",
  "text": "[Main] You may rest 2 of your DON!! cards: K.O. up to 1 of your opponent&#39;s Stages. [Counter] If you have 2 or more Characters with a [Trigger], up to 1 of your Leader or Characters gains +4000 power during this battle.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "UC",
  "color": "Yellow",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-116.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-117",
  "name": "Maser Saber",
  "text": "[Counter] Up to 1 of your [Charlotte Linlin] cards gains +3000 power during this battle. [Trigger] Your opponent may trash 3 cards from their hand. If they don&#39;t, K.O. up to 1 of your opponent&#39;s Characters with a cost of 6 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "C",
  "color": "Yellow",
  "type": "Event",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-117.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-118",
  "name": "Rocks.D.Xebec",
  "text": "If you only have Characters without a Counter, this card in your hand has a +2000 Counter. [On Play] Draw 1 card and play up to 2 {Rocks Pirates} type cards with different card names and a total cost of 9 or less from your hand.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SEC",
  "color": "Blue Red",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-118.jpg",
  "spoiler": true
 },
 {
  "id": "OP17-119",
  "name": "Loki",
  "text": "This character&#39;s cost increases by 12, and if it&#39;s your opponent&#39;s turn, this character&#39;s power increases by 3000. [On Play] KO your opponent&#39;s characters so that their total cost is 4 or less.",
  "set": "The World’s Strongest Warriors (spoilers)",
  "setId": "OP-17",
  "rarity": "SEC",
  "color": "Yellow Blue",
  "type": "Character",
  "life": null,
  "cost": null,
  "power": null,
  "subs": "",
  "counter": null,
  "attr": "",
  "img": "op17/OP17-119.png",
  "spoiler": true
 }
];
